In [1]:
%load_ext autoreload
%autoreload 2

In [151]:
import numpy as np
import plotly.graph_objects as go
from willitfit.plotting import plotter, plot_helper
from willitfit.app_utils.trunk_dimensions import get_volume_space
from scipy.ndimage import convolve
import pandas as pd
import os
from pathlib import Path

In [160]:
from willitfit.params import VOL_UNAVAILABLE, VOL_EMPTY

# Unavailable space

### Define unavailable space

In [176]:
vol_space = np.zeros((6,6,6), dtype=int)
vol_space[0:4,0:4,0:4] = VOL_UNAVAILABLE
vol_space[4:6,0:4,0:2] = VOL_UNAVAILABLE

In [177]:
vol_space

array([[[-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0]],

       [[-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0]],

       [[-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0]],

       [[-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [-1, -1, -1, -1,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0]],

       [[-1, -1,  0,  0,  0,  0],
        [-1, -1,  0,  0,  0,  0],
        [-1, -1,  0,  0,  0,  0],
        [-1, -1,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
      

In [166]:
article = [['Article','0','0',0,4,0,1,6,2]]

In [178]:
plotter.plot_all(vol_space, article, plot_unavailable=True)

In [168]:
w = [[[0,0,0],
      [0,1,0],
      [0,0,0]],
     [[0,1,0],
      [1,1,1],
      [0,1,0]],
     [[0,0,0],
      [0,1,0],
      [0,0,0]]]
w = np.array(w)

In [169]:
w

array([[[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [1, 1, 1],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]]])

In [170]:
convolved = convolve(vol_space,w, mode='constant', cval=0.0)
convolved

array([[[4, 5, 5, 4, 1, 0],
        [5, 6, 6, 5, 1, 0],
        [5, 6, 6, 5, 1, 0],
        [4, 5, 5, 4, 1, 0],
        [1, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[5, 6, 6, 5, 1, 0],
        [6, 7, 7, 6, 1, 0],
        [6, 7, 7, 6, 1, 0],
        [5, 6, 6, 5, 1, 0],
        [1, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[5, 6, 6, 5, 1, 0],
        [6, 7, 7, 6, 1, 0],
        [6, 7, 7, 6, 1, 0],
        [5, 6, 6, 5, 1, 0],
        [1, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[5, 6, 5, 4, 1, 0],
        [6, 7, 6, 5, 1, 0],
        [6, 7, 6, 5, 1, 0],
        [5, 6, 5, 4, 1, 0],
        [1, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[5, 5, 2, 1, 0, 0],
        [6, 6, 2, 1, 0, 0],
        [6, 6, 2, 1, 0, 0],
        [5, 5, 2, 1, 0, 0],
        [1, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[4, 4, 1, 0, 0, 0],
        [5, 5, 1, 0, 0, 0],
        [5, 5, 1, 0, 0, 0],
        [4, 4, 1, 0, 0, 0],
        [1, 1, 0, 0, 0, 0],
        [0

In [171]:
edges = np.argwhere((convolved < 6) & (convolved > 3))
edges.T

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3,
        3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5],
       [0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 3, 3, 0, 0, 3, 3, 0, 0, 3, 3, 0, 0,
        0, 1, 2, 3, 3, 3, 0, 0, 3, 3, 0, 0, 1, 1, 2, 2, 3, 3],
       [0, 1, 2, 3, 0, 3, 0, 3, 0, 1, 2, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 2,
        3, 3, 3, 0, 2, 3, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]])

In [172]:
mesh = plotter.generate_mesh3d_from_coords([edges.T])

In [173]:
plotter.draw_3d_plot(mesh, vol_space.shape)

# Test with car data

In [156]:
def get_volume_space(car_model, data, ratio_height=0.5, ratio_depth=0.5, rate_of_slant=2):
    """
    Returns available volume for a specific car_model.
    Use ratio_door to tweak estimated unavailable space caused by 45-degree trunk-door slope.
    """
    # Isolate dimension cols
    dim_cols = ['depth', 'height', 'width']

    # Trunk dimensions
    model_row = data[data['car_model'] == car_model]
    trunk_dims = model_row[dim_cols].to_numpy(int)[0]

    # Cuboid Volume Space
    volume_space = np.full(trunk_dims, VOL_EMPTY, dtype=int)

    # Unavailable space
    height_block = int(trunk_dims[1]*ratio_height)
    depth_block = int(trunk_dims[0]*ratio_depth)
    for i in range(1, depth_block):
        volume_space[i,height_block:int(rate_of_slant)*i,:] = VOL_UNAVAILABLE

    return volume_space


In [157]:
def test_unavailable_space(car_model, data, ratio_height, ratio_depth, rate_of_slant):
    test_vol = get_volume_space(car_model=car_model, data=data, ratio_height=ratio_height, ratio_depth=ratio_depth, rate_of_slant=rate_of_slant)
    return plotter.plot_all(test_vol, plot_unavailable=True)

In [158]:
CSV_PATH = Path(os.path.abspath(os.getcwd())).parent.absolute()/"willitfit/data/cars_clean.csv"
print(CSV_PATH)
data = pd.read_csv(CSV_PATH)
car_model = data.iloc[250]['car_model']

/home/dominik/code/domzae/willitfit/willitfit/data/cars_clean.csv


In [162]:
test_unavailable_space(car_model=car_model, data=data, ratio_height=0.5, ratio_depth=0.5, rate_of_slant=2)